(function() {
    'use strict';
    /*global QUnit,kg*/

    QUnit.module("Grid Tests");

    QUnit.test("Basic Grid Test", function(assert) {

        var data = ko.observableArray([{ prop1: 'test1', prop2: 'test2'}]);

        var grid = new kg.KoGrid({
            data: data,
            autogenerateColumns: true
        });

        assert.ok(grid, 'Grid Instantiated!');
        assert.equals(grid.columns().length, 4, 'Autogenerated 4 Columns'); //4 columns bc of RowIndex and Selected
    });
})();
